### ISSUE TITLE
[Bug]: Game doesnt load with melonloader

### ISSUE THREAD

**Issue by ImThatPotato** [LavaGang/MelonLoader#553] opened 2023-10-21 16:58 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

whenever I launch melonloader, 0.62 (64x) the game crashes.

[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[12:55:30.132] ------------------------------
[12:55:30.133] MelonLoader v0.6.1 Open-Beta
[12:55:30.134] OS: Windows 10
[12:55:30.134] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[12:55:30.134] ------------------------------
[12:55:30.135] Game Type: Il2cpp
[12:55:30.135] Game Arch: x64
[12:55:30.135] ------------------------------
[12:55:30.135] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[12:55:30.135] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[12:55:30.135] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[12:55:30.136] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[12:55:30.136] Runtime Type: net6
[12:55:30.240] ------------------------------
[12:55:30.241] Game Name: BloonsTD6
[12:55:30.241] Game Developer: Ninja Kiwi
[12:55:30.242] Unity Version: 2022.3.7f1
[12:55:30.243] Game Version: 39.2
[12:55:30.243] ------------------------------

[12:55:30.892] Preferences Loaded!

[12:55:30.972] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Plugins'...
[12:55:30.974] 0 Plugins loaded.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment] 2023-10-21 17:17
Fixed in nightly, duplicate of #541

**Closed as completed by RinLovesYou** 2023-10-21 17:17 UTC
