### ISSUE TITLE
[Bug]: My Melonloader Panel shows <0 Plugins> Then Closed itself instantly without showing me any error

### ISSUE THREAD

**Issue by M04I** [LavaGang/MelonLoader#587] opened 2023-12-01 23:28 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

>When i open bloons td 6 the melonloader panel opens right after that it shows 0 plugins and then just crashed no errors just crashed i already check "Game Directory" Melonloader theres no latest log pls help

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-12-02 00:42
Duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Closed as not planned by rakosi2** 2023-12-02 00:42 UTC
