### ISSUE TITLE
[Bug]: Btd6 not launching with melon loader

### ISSUE THREAD

**Issue by Kb0lt** [LavaGang/MelonLoader#556] opened 2023-10-22 17:20 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Btd6 isnt launching the melon loader cmd page just says 0 plugins loaded at the end and then btd6 doenst launch . Please no one close this ticket unless u showed me how to fix it.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RamboNotnats** [comment] 2023-10-29 23:50
I had this for so long, but i think i finally fixed it.
Open melonloader, turn off auto-detect game arch, and set it to x86. Then just re-install.

**Comment by Renster21** [comment] 2023-11-04 23:06
I Have a AMD Prossesor and does not let me download .Net 6.0 so what can i do

**Comment by lunndal** [comment] 2023-11-05 20:20
I'm seeing the same issue. I'm attaching my Latest.log below. Any help in troubleshooting is much appreciated.

```
[21:14:26.195] [DEBUG] Initializing Analytics Blocker...
[21:14:26.241] [DEBUG] Hooking wsock32::gethostbyname (0x7FFEABE766D0)...
[21:14:26.248] [DEBUG] Hooking ws2_32...
[21:14:26.284] ------------------------------
[21:14:26.285] MelonLoader v0.6.1 Open-Beta
[21:14:26.286] OS: Windows 10
[21:14:26.287] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[21:14:26.287] ------------------------------
[21:14:26.287] Game Type: Il2cpp
[21:14:26.288] Game Arch: x64
[21:14:26.288] ------------------------------
[21:14:26.288] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[21:14:26.289] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[21:14:26.289] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[21:14:26.289] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[21:14:26.289] Runtime Type: net6
[21:14:26.425] ------------------------------
[21:14:26.426] Game Name: BloonsTD6
[21:14:26.426] Game Developer: Ninja Kiwi
[21:14:26.429] Unity Version: 2022.3.7f1
[21:14:26.429] Game Version: 39.2
[21:14:26.430] ------------------------------

[21:14:26.434] [DEBUG] [MonoLibrary] Caught SecurityException, assuming not running under mono and continuing with init
[21:14:27.308] Preferences Loaded!
[21:14:27.312] [DEBUG] Ignoring MelonModule 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\CompatibilityLayers\IPA.dll'...

[21:14:27.343] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Plugins'...
[21:14:27.346] 0 Plugins loaded.
```

**Comment by rakosi2** [comment] 2023-11-11 21:39
Fixed in nightly, duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Closed as completed by rakosi2** 2023-11-11 21:39 UTC
