### ISSUE TITLE
Btd6 crashes on launch

### ISSUE THREAD

**Issue by VedatCingoz** [LavaGang/MelonLoader#559] opened 2023-10-28 13:19 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13195854/Latest.log)
[Latest-Bootstrap.log](https://github.com/LavaGang/MelonLoader/files/13195860/Latest-Bootstrap.log)

Ever since the recent update of btd6, my game has been crashing on my desktop whenever I try to run it with melonloader. I have tried deleting all my mods, and opening debug mode to see if it was an issue I could fix but I do not understand what the problem is.

It has been running fine on my laptop and I can't really figure out what the differences are between my desktop and laptop besides my laptop being windows 11.

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment] 2023-10-28 13:27
Fixed in nightly, duplicate of #541

**Closed as completed by rakosi2** 2023-10-28 13:27 UTC
