### ISSUE TITLE
[Bug]: No Support Module Loaded

### ISSUE THREAD

**Issue by jcc2010tw** [LavaGang/MelonLoader#354] opened 2022-12-18 09:38 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [x] Was able to see the Start Screen.

### Describe the issue.

Im new to modding and im trying to install mods for BTD6. The this thing popped up and then the game would get stuck on step 1 of 7 loading screen.
[MelonLoader_22-12-18_17-10-27.925.log](https://github.com/LavaGang/MelonLoader/files/10253519/MelonLoader_22-12-18_17-10-27.925.log)

Heres the log. pretty sure u can download the file by copying the url.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment] 2022-12-18 09:41
Known issue, fixed in nightly, wait for the next release

**Comment by HerpDerpinstine** [comment] 2022-12-19 00:56
Duplicate of #322

**Closed as not planned** 2022-12-19 00:57 UTC
Labels: Duplicate, Invalid
