### ISSUE TITLE
[Bug]: bloons wont open

### ISSUE THREAD

**Issue by skullgamer932** [LavaGang/MelonLoader#561] opened 2023-10-29 21:01 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

when i try to open bloons it crasehes without going on to the loading screan.

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-10-29 21:21
Duplicate of #541

**Closed as completed by rakosi2** 2023-10-29 21:21 UTC
