### ISSUE TITLE
[Bug]: When launching BTD6, doesn't launch at all

### ISSUE THREAD

**Issue by IceandFire04** [LavaGang/MelonLoader#578] opened 2023-11-21 17:31 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[12:29:00.741] ------------------------------
[12:29:00.774] MelonLoader v0.6.1 Open-Beta
[12:29:00.775] OS: Windows 11
[12:29:00.775] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[12:29:00.775] ------------------------------
[12:29:00.775] Game Type: Il2cpp
[12:29:00.775] Game Arch: x64
[12:29:00.776] ------------------------------
[12:29:00.776] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[12:29:00.776] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[12:29:00.776] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[12:29:00.776] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[12:29:00.776] Runtime Type: net6
[12:29:00.871] ------------------------------
[12:29:00.872] Game Name: BloonsTD6
[12:29:00.872] Game Developer: Ninja Kiwi
[12:29:00.874] Unity Version: 2022.3.7f1
[12:29:00.874] Game Version: 39.2
[12:29:00.874] ------------------------------

//the following was copied from the window and wasn't written in the log file
[NewEntryPoint] Caught exception invoking Initialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
   at HarmonyLib.Harmony..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.Harmony..ctor(String id)
   at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 72
   at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
   at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment] 2023-11-21 18:10
Duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Closed as completed by rakosi2** 2023-11-21 18:10 UTC
