### ISSUE TITLE
[Bug]: Crashes when installing Bone Lib

### ISSUE THREAD

**Issue by KOFEid** [LavaGang/MelonLoader#660] opened 2024-06-10 11:24 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/15764832/Latest.log)
In the initial screen, the download reaches the installation of Bone Lib and crashes without errors

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by SamboyCoding** [comment] 2024-06-10 11:40
Duplicate of #656. See that thread for info.

**Closed as not planned by SamboyCoding** 2024-06-10 11:40 UTC
