### ISSUE TITLE
[Bug]: Coroutines not working

### ISSUE THREAD

**Issue by ZereX666** [LavaGang/MelonLoader#377] opened 2023-01-14 12:27 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [x] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Coroutines stopped working after the game updated the Unity version from 2018.4.2f1 to 2021.3.10f1

```
MelonLogger.Msg("1");
yield return new WaitForSeconds(2f);
MelonLogger.Msg("2");
yield return null;
```

```
[14:24:46.946] [LM_Additions] 1
[14:24:46.950] [LM_Additions] 2
```

New Unity Version: 2021.3.10f1 (don`t work)
Old Unity Version: 2018.4.2f1

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by TrevTV** [comment] 2023-01-14 17:39
Sounds like a duplicate of #327

**Comment by HerpDerpinstine** [comment] 2023-01-14 17:50
Closing due to being a duplicate of #327

**Closed as completed by HerpDerpinstine** 2023-01-14 17:50 UTC
Labels: Duplicate, Invalid
