### ISSUE TITLE
[Bug]: House Party crashes at main menu, DLL initialization routine failed

### ISSUE THREAD

**Issue by CamelCaseName** [LavaGang/MelonLoader#333] opened 2022-12-11 20:42 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When using House Pary 1.0.6 with Melonloader > 0.5.3, so for example the latest 0.5.7, it starts, loading screen shows, and after you click in the disclaimer it crashes going to the main menu. 

Unity crash log shows 
`========== OUTPUTTING STACK TRACE ==================

0x00007FFD22BFFBB8 (GameAssembly) DllGetActivationFactory
  ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 00000289F1FBED98)
  ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 00000289F1FBED98)
0x00000289F1FBED98 ((<unknown>)) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 0000028A9B2D0CF5)
  ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 0000028A9B2D0CF5)
0x0000028A9B2D0CF5 ((<unknown>)) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'The specified module could not be found.' (Address: 00000289F1FBEB23)
  ERROR: SymGetModuleInfo64, GetLastError: 'A dynamic link library (DLL) initialization routine failed.' (Address: 00000289F1FBEB23)
0x00000289F1FBEB23 ((<unknown>)) (function-name not available)
0x00007FFD22BCC179 (GameAssembly) UnityPalGetTimeZoneDataForID
0x00007FFD23EAC0BE (GameAssembly) WriteZStream
[...]`
as the stack trace. same stack trace also happens with Bepinex, so it is probably an underlying component.

Same thing happens regardless, whether mods are present or not 

[Latest.log](https://github.com/LavaGang/MelonLoader/files/10203242/Latest.log)

[Player.log](https://github.com/LavaGang/MelonLoader/files/10203236/Player.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment] 2022-12-11 21:21
Duplicate of #322 and fixed in nightly

**Closed as not planned by SamboyCoding** 2022-12-11 21:21 UTC
Labels: Duplicate, Invalid

**Comment by nitrog0d** [comment] 2022-12-11 21:22
house party 💀
