### ISSUE TITLE
[Bug]: .NET 6.0 runtime

### ISSUE THREAD

**Issue by Username1234567890000000** [LavaGang/MelonLoader#488] opened 2023-07-09 23:37 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When ever i launch Melon loader from the game i get a error message saying "il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime.
[00:36:02.822] [ERROR] il2cpp_init detour failed: Failed to load hostfxr. Please make sure you have installed the .NET 6.0 runtime."

please can somebody tell me how to fix this

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-07-09 23:40
Did you install .NET 6.0 runtime like it asked?

**Comment by rakosi2** [comment] 2023-07-09 23:42
Duplicate of #367

**Comment by RinLovesYou** [comment] 2023-07-09 23:43
closing, not a bug

**Closed as completed by RinLovesYou** 2023-07-09 23:43 UTC
Labels: Invalid, User Support

**Comment by mccad00** [comment] 2023-07-10 00:22
Has anyone found the fix for this?

**Comment by lavvydaddy** [comment] 2023-09-14 20:44
where do you download net 6.0 thing

**Comment by rakosi2** [comment] 2023-09-14 20:45
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Get Desktop runtime x64

**Comment by PranitModak** [comment] 2023-10-08 14:39
@rakosi2 

![image](https://github.com/LavaGang/MelonLoader/assets/43670565/d9f8af92-3ef9-490a-866a-10ba837c64c5)

**I have tried installing all different kinds of runtime still getting this error.**

![image](https://github.com/LavaGang/MelonLoader/assets/43670565/b1dd0b45-d1ac-4c44-8285-4ce90d9f9f8c)

**Comment by babyfolder** [comment] 2023-10-15 15:43
Same happens to me but I get the error "il2cpp_init detour failed: It was not possible to find a compatible framework version." and I have installed like 5 different NET 6.0 versions. 

Edit: I have now downgraded melonloader to 5.7.0 and it works!... Except when I add the Btd6ModHelper.dll file to the mods folder it just closes.

**Comment by matannn12** [comment] 2023-10-17 11:35
> Same happens to me but I get the error "il2cpp_init detour failed: It was not possible to find a compatible framework version." and I have installed like 5 different NET 6.0 versions.
> 
> Edit: I have now downgraded melonloader to 5.7.0 and it works!... Except when I add the Btd6ModHelper.dll file to the mods folder it just closes.
HI! same here.
please tell me if you were able to add mods with the 5.7.0 version or found a way to fix it.
thanks!
