### ISSUE TITLE
[Bug]: BTD6 crash on startup

### ISSUE THREAD

**Issue by an0nLogin** [LavaGang/MelonLoader#543] opened 2023-10-14 06:12 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12903050/Latest.log)
Starting BTD6 shows the console for a few seconds then closes.

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-10-14 07:36
Duplicate of #541

**Closed as completed by rakosi2** 2023-10-14 07:36 UTC
