### ISSUE TITLE
[Bug]: Btd6 not launching when i have melon loader installed

### ISSUE THREAD

**Issue by Kb0lt** [LavaGang/MelonLoader#554] opened 2023-10-22 02:55 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Whenever I go to launch my btd6 with melon loader in the melon loader cmd page it runs code and the last tjing it says is 0 plugins loaded and then just doesnt launch btd6 and the cmd page goes away. Ive tried everything and nothing seems to be working. Can someone pleas respond and help me :(.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-10-22 02:57
fixed in nightly, duplicate of #541

**Comment by Kb0lt** [comment] 2023-10-22 17:19
this was not fixed

**Comment by Kb0lt** [comment] 2023-10-22 17:19
someone closed this for me

**Comment by rakosi2** [comment] 2023-10-22 17:21
Ok, send us a log

**Comment by lunndal** [comment] 2023-11-05 20:23
I've supplied a log example for the same issue in #556

**Comment by rakosi2** [comment] 2023-11-11 21:40
Closed due to inactivity from issue creator, This issue is resolved in MelonLoader nightly, make sure that version is 0.6.2

**Closed as completed by rakosi2** 2023-11-11 21:40 UTC
