### ISSUE TITLE
[Bug]: instant crash

### ISSUE THREAD

**Issue by Ghosto7** [LavaGang/MelonLoader#574] opened 2023-11-15 23:30 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

when i open the game melon loader loads then instantly crashes and i cant find anything like this except people using 3rd party launcher but i dont use a 3rd party launcher.

[17:25:33.282] ------------------------------
[17:25:33.308] MelonLoader v0.6.1 Open-Beta
[17:25:33.309] OS: Windows 11
[17:25:33.309] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[17:25:33.309] ------------------------------
[17:25:33.310] Game Type: Il2cpp
[17:25:33.310] Game Arch: x64
[17:25:33.310] ------------------------------
[17:25:33.310] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6 - Copy
[17:25:33.311] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6 - Copy
[17:25:33.311] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6 - Copy\BloonsTD6_Data
[17:25:33.311] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6 - Copy\BloonsTD6.exe
[17:25:33.312] Runtime Type: net6
[17:25:33.491] ------------------------------
[17:25:33.492] Game Name: BloonsTD6
[17:25:33.492] Game Developer: Ninja Kiwi
[17:25:33.493] Unity Version: 2022.3.7f1
[17:25:33.493] Game Version: 39.2
[17:25:33.493] ------------------------------

[17:25:34.615] Preferences Loaded!

[17:25:34.695] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6 - Copy\Plugins'...
[17:25:34.697] 0 Plugins loaded.

idk code but looks normal

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by rakosi2** [comment] 2023-11-15 23:40
Duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Closed as completed by rakosi2** 2023-11-15 23:40 UTC

**Comment by Ghosto7** [comment] 2023-11-16 00:08
well then fix it and there wont be issues

**Comment by AlphaLovesYou** [comment] 2023-11-16 05:21
> well then fix it and there wont be issues

fix is in the issue that this is marked as a duplicate of as well as in the melon loader discord under the "btd6" channel.
