### ISSUE TITLE
[Bug]: Farthest Frontier game launches fine even loads to save but no mods.

### ISSUE THREAD

**Issue by sader22** [LavaGang/MelonLoader#387] opened 2023-01-29 15:34 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

As you can see from log there exist an error and i guess because of tat I cant even load mods. Game launches fine even loads to save but no mods.
[MelonLoader_23-01-29_18-26-35.794.log](https://github.com/LavaGang/MelonLoader/files/10530089/MelonLoader_23-01-29_18-26-35.794.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by Azoren-24332** [comment] 2023-01-29 21:45
For what it's worth, I was experiencing that error in beta 0.5.7 but I'm not in alpha 0.6.0. I am however, experiencing a different error in 0.6.0:

`[08:32:21.616] [Il2CppAssemblyGenerator] Error Generating Interop Assemblies!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppInterop.Generator.Contexts.AssemblyRewriteContext.RewriteTypeRef(TypeReference typeRef) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Contexts/AssemblyRewriteContext.cs:line 133
   at Il2CppInterop.Generator.Passes.Pass12FillTypedefs.DoPass(RewriteGlobalContext context) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass12FillTypedefs.cs:line 33
   at Il2CppInterop.Generator.Runners.InteropAssemblyGeneratorRunner.Run(GeneratorOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs:line 79
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Start() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 30
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Run() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 47
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.ExecuteInterop() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 97
`

But I don't want to hijack this ticket so I'll leave it at that - looks like both mine and OP's errors are pointing to the assemblies - potentially the same cause?

**Comment by donimuzur** [comment] 2023-01-30 01:46
im having the same error,

**Comment by Azoren-24332** [comment] 2023-01-31 05:43
Also this ticket looks to be a duplicate of #378

**Comment by SamboyCoding** [comment] 2023-02-04 19:15
As of just now, 0.6.0 should work on Farthest Frontier.

**Closed as completed by SamboyCoding** 2023-02-04 19:15 UTC

**Comment by sader22** [comment] 2023-02-05 09:52
nope here you go with the latest log all other mods also have same error
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10610635/Latest.log)
[Latest.log](https://github.com/LavaGang/MelonLoader/files/10610637/Latest.log)

**Comment by damasioj** [comment] 2023-02-05 13:21
Yes it's working now without errors. I had to do a few extra steps to get my mods to work correctly:

- Update the mod to .NET 6 framework (as stated on the wiki)
- Reference assemblies in the MelonLoader/Managed folder (as stated on the wiki)
- Reference assemblies in the MelonLoader/net6 folder
- Update my mod's references
- Replace UnhollowerLib references with Il2cppInterop.Runtime

Please update the wiki guide to include the third line as it's needed for il2cpp based games.
