### ISSUE TITLE
[Bug]: Melonloader opens then closes

### ISSUE THREAD

**Issue by BB44YT** [LavaGang/MelonLoader#572] opened 2023-11-11 18:30 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

When i open btd6 the melonloader intro starts(the commands) and then it closes. i dont have mods installed rn

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-11-11 21:36
Fixed in nightly, duplicate of https://github.com/LavaGang/MelonLoader/issues/541

**Closed as completed by rakosi2** 2023-11-11 21:36 UTC
