### ISSUE TITLE
Game Crashes during Initialization [Bug]: 

### ISSUE THREAD

**Issue by Gamerzkingdom** [LavaGang/MelonLoader#544] opened 2023-10-14 07:16 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

(Steam)
I tried opening Modded BTD6 after a while of not playing. Updated MelonLoader and wiped old mods and put in a new instance of BTD6ModHelper. But the game kept crashing. I tried completely uninstalling and reinstalling both BTD6 and MelonLoader, even on different drives, then uninstalled and reinstalled Visual C++ and Net 6.0 Framework. I then got a fresh install of both BTD6 and MelonLoader, still getting stuck at the same process in initializing the game.  

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12903275/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment] 2023-10-14 07:36
Duplicate of #541

**Closed as completed by rakosi2** 2023-10-14 07:36 UTC
