### ISSUE TITLE
[Bug]: Not updated/doesn't work with btd6 v34

### ISSUE THREAD

**Issue by KingOfAllPears** [LavaGang/MelonLoader#332] opened 2022-12-11 19:19 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

It doesn't work with the new btd6 update v34

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment] 2022-12-11 19:50
Duplicate of #322 
fixed in nightly

**Closed as completed** 2022-12-11 20:44 UTC
Labels: Duplicate, Invalid
